# Project Euler: Problem 2
# Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
#   
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
#  find the sum of the even-valued terms.

#MAX_VALUE <- 40
MAX_VALUE <- 4000000

# Let's make a vector to collect our target values
evenFibonacciValues <- NULL

# we will use 3 control variables, i and j for the previous two values and k for the current value
i <- 1
j <- 1
k <- 2

while (k <= MAX_VALUE) {
  # if j is even, append it to our vector
  if(k %% 2 == 0) {
    evenFibonacciValues <- c(evenFibonacciValues, k)
  }
  
  # shift the values of our control variables and compute the next value
  i <- j
  j <- k
  k <- i + j
}

# sum all of our even Fibonacci numbers
sum(evenFibonacciValues)